# Generated by Django 6.1 on 2026-09-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('organization', 'Organization'), ('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], default='full-time', max_length=20),
        ),
    ]
