# Generated by Django 6.1 on 2026-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('ongoing', 'In progress')], default='ongoing', max_length=10)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
            ],
        ),
    ]
